### ISSUE TITLE
Переименовать IConvertToEntity в IConvertable

### ISSUE THREAD

**Issue by Sod3n** [aleverdes/leoecslite-zoo#10]
ConvertToEntity и IConvertToEntity из-за их нейминга, как по мне вызывают путаницу. Буд-то бы ConvertToEntity должен реализовывать IConvertToEntity, но на самом деле их функционал разный.

**Comment by aleverdes** [comment]
Могу предложить `IConvertableToEntity`, вроде не вызывает путаницы, удовлетворяет неймингу интерфейсов, и не сильно отличается от текущей реализации. Если ок, то завтра сделаю Obsolete на `IConvertToEntity` и переедем на `IConvertableToEntity`

**Comment by Sod3n** [comment]
Извините, пропал с гита на несколько дней. Да, так будет звучать даже более правильно.

**Comment by aleverdes** [comment]
Сделано.
